### ISSUE TITLE
Python binding support for the Program type

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quil-rs#121]
To support a robust and fluent Python ecosystem (see QCS SDK Rust) we should provide comprehensive Python support for the `quil_rs::Program` type, and it hew close to the [interface presented by `pyquil.Program`](https://github.com/rigetti/pyquil/blob/master/pyquil/quil.py#L114).

Before working on this issue we should have a plan for

* what is supported
* what is deprecated (but supported)
* what is not supported

and we should have input from intended users (e.g. @caldwellshane and @jokasinski).

**Comment by jselig-rigetti** [comment]
RE https://github.com/rigetti/pyquil/issues/1455 make sure to support LaTeX generation

**Comment by MarquessV** [comment]
# Ready to work

## Instruction API:

Unless otherwise stated, each of these needs:

1. A `new` constructor, w/ validations (if applicable).
2. Corresponding Python bindings.
3. Mapped to the corresponding pyQuil `AbstractInstruction` or `QuilAtom` subclass.

Complexity commonly arises in (1) when the type doesn't cleanly translate to something that can be mapped 
to a pyo3 binding (e.g. enum struct variants). Extra complexity also pops up in (3) when a quil-rs
`Instruction` doesn't cleanly map to a pyQuil type (e.g. `Arithmetic`), limitations with pyO3
(e.g. not being able to pickle pyo3 types, or subclass enums), or `quil-rs` is missing functionality
(e.g. declarations w/ `OFFSET`).

### Remaining instructions:

- [ ] Arithmetic (pyQuil only)
- [ ] BinaryLogic (pyQuil only)
- [ ] Capture
- [ ] CircuitDefinition
- [ ] Convert
- [ ] Comparison
    - [ ] ComparisonOperator
    - [ ] ComparisonOperand
- [ ] Declaration (needs OFFSET support)
- [ ] Delay
- [ ] Exchange
- [ ] Fence
- [ ] GateDefinition (pyQuil only)
- [ ] Include
- [ ] Jump
- [ ] JumpUnless
- [ ] JumpWhen
- [ ] Label
- [ ] Load
- [ ] Move
- [ ] Pragma
    - [ ] PragmaArgument
- [ ] Pulse
- [ ] RawCapture
- [ ] Reset
- [ ] SetFrequency
- [ ] SetPhase
- [ ] SetScale
- [ ] ShiftFrequency
- [ ] ShiftPhase
- [ ] Store
- [ ] SwapPhases
- [ ] UnaryLogic
    - [ ] UnaryOperator
- [ ] Wait (no-variant)
- [ ] WaveformDefinition

## Parsing Fixes:

- [ ] GateDefinition: Parameter parsing (%)
- [ ] `PRAGMA READOUT-POVM` fails to parse, probably the `-`

## Program Unitary

- [ ] Port `program_unitary` to `quil-rs` and add a binding

## Release Engineering

- [ ] Re-configure knope with scopes for each package.
- [ ] CI flows for building wheels and publishing the package.
- [ ] Figure out how to bundle `quil-py` with `qcs-sdk-python`
    - Either:
        - Define `quil-py` as a required dependency of `qcs-sdk-python`
        - Re-export with a build script

## Pickling

Some parts of pyQuil pickle `Program`, but quil-rs' `Program` can't be pickled. Needs discovery.
Tracked by [quil-rs#169](https://github.com/rigetti/quil-rs/issues/169)

## quil-rs Features:

- [ ] Support Declaration `OFFSET`s [quil-rs#171](https://github.com/rigetti/quil-rs/issues/171)

## Expressions API

- [X] Expressions API Python Binding [quil-rs#168](https://github.com/rigetti/quil-rs/pull/168)
- [ ] Use Expressions API in pyQuil

## Misc

- [ ] Deprecate `quilatom.format_parameter`
- [ ] Deprecate `PRAGMA Delay` in pyQuil, use `DELAY` instruction instead
    - [ ] Will probably require fixing [quil-rs#146](https://github.com/rigetti/quil-rs/issues/146)
- [ ] Remove `to_headers()` [quil-rs#151](https://github.com/rigetti/quil-rs/issues/151)
- [ ] `get_match_for_measurement` should follow precedence rules [quil-rs#160](https://github.com/rigetti/quil-rs/issues/160)

# Blocked

## Control Flow Methods

- [ ] Needs by Qubit and Label Placeholders in [quil-rs#147](https://github.com/rigetti/quil-rs/issues/147)
    - [ ] Update bindings to use `Display::to_string()` to `Quil::to_quil()`
    - [ ] Python bindings
    - [ ] Use it in pyQuil

## Endgame

- [ ] Docs sweep and update
- [ ] Migration guide
- [ ] CHANGELOG

## LaTeX Module

- [ ] In progress by @hiyaryan [quil-rs#145](https://github.com/rigetti/quil-rs/pull/145)

## Finished

### Instruction API

Via:

1. [quil-rs#140](https://github.com/rigetti/quil-rs/pull/140)

2. [pyQuil#1518](https://github.com/rigetti/pyquil/pull/1518)

3. [quil-rs#168](https://github.com/rigetti/quil-rs/pull/168)

4. [pyQuil#1542](https://github.com/rigetti/pyquil/pull/1542)

### Instruction Types

- [X] CalibrationDefinition
- [X] FrameDefinition
- [X] Gate
- [X] Halt
- [X] MeasureCalibrationDefinition
- [X] Measurement
- [X] Nop

### Supporting Types:

#### Arithmetic

- [X] ArithmeticOperand
- [X] ArithmeticOperator
- [X] BinaryOperand
- [X] BinaryOperands
- [X] BinaryOperator

#### Declaration

- [X] MemoryReference
- [X] ScalarType
- [X] Vector

#### Frame

- [X] AttributeValue
- [X] FrameIdentifier

#### Gate

- [X] GateDefinition
- [X] GateModifier
- [X] GateSpecification
- [X] Qubit

#### Waveform

- [X] Waveform
- [X] WaveformInvocation

#### Other

- [X] Re-implement get_classical_addresses_from_quil_program [pyQuil#1451](https://github.com/rigetti/pyquil/pull/1541)
- [X] CalibrationSet API [quil-rs#156](https://github.com/rigetti/quil-rs/pull/156), [pyQuil#1536](https://github.com/rigetti/pyquil/pull/1536)
- [X] FrameSet API [quil-rs#170](https://github.com/rigetti/quil-rs/pull/170), [pyQuil#1543](https://github.com/rigetti/pyquil/pull/1543)
